### ISSUE TITLE
Failed to fetch llama.cpp release info RequestError [HttpError]: Not Found

### ISSUE THREAD

**Issue by loretoparisi** [withcatai/node-llama-cpp#25]
I'm running the basic example provided in the `README.md` but I get an error when the library tries to fetch the `llama.cpp`
```bash
root@981b3099966c:/app# node example.js 
Prebuild binaries not found, falling back to to locally built binaries
Repo: ggerganov/llama.cpp
Release: /app/llama.cpp

⠋ Fetching llama.cpp info(node:75) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
⠦ Fetching llama.cpp infoFailed to fetch llama.cpp release info RequestError [HttpError]: Not Found
    at /app/node_modules/@octokit/request/dist-node/index.js:112:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/app/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/ggerganov/llama.cpp/releases/tags/%2Fapp%2Fllama.cpp',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-length': '117',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 31 Aug 2023 13:28:37 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '819E:7616:24960C:24DD3C:64F09584',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '57',
      'x-ratelimit-reset': '1693492072',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '3',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/ggerganov/llama.cpp/releases/tags/%2Fapp%2Fllama.cpp',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.0 octokit-core.js/5.0.0 Node.js/18.0.0 (linux; arm64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}
✖ Failed to fetch llama.cpp info
file:///app/dist/cli/commands/DownloadCommand.js:103
            throw new Error(`Failed to find release "${release}" of "${repo}"`);
                  ^

Error: Failed to find release "/app/llama.cpp" of "ggerganov/llama.cpp"
    at file:///app/dist/cli/commands/DownloadCommand.js:103:19
    at async withOra (file:///app/dist/utils/withOra.js:6:21)
    at async DownloadLlamaCppCommand (file:///app/dist/cli/commands/DownloadCommand.js:79:5)
    at async loadBin (file:///app/dist/utils/getBin.js:57:13)
    at async file:///app/dist/llamaEvaluator/LlamaBins.js:2:29

Node.js v18.0.0
root@981b3099966c:/app#
```

The env variable `NODE_LLAMA_CPP_REPO_RELEASE` is set:
```bash
root@981b3099966c:/app# echo $NODE_LLAMA_CPP_REPO_RELEASE
/app/llama.cpp
```

I have also set the skip download, but it fails searching for the binaries:

```bash
root@981b3099966c:/app# echo $NODE_LLAMA_CPP_SKIP_DOWNLOAD
1
root@981b3099966c:/app# node example.js 
Prebuild binaries not found, falling back to to locally built binaries
file:///app/dist/utils/getBin.js:54
            throw new Error("No prebuild binaries found and NODE_LLAMA_CPP_SKIP_DOWNLOAD env var is set to true");
                  ^

Error: No prebuild binaries found and NODE_LLAMA_CPP_SKIP_DOWNLOAD env var is set to true
    at loadBin (file:///app/dist/utils/getBin.js:54:19)
    at async file:///app/dist/llamaEvaluator/LlamaBins.js:2:29

Node.js v18.0.0
```

The only way I get it working is via downloading via CLI:
```
RUN cd $ROOT_APPLICATION && npx --yes node-llama-cpp download --release latest --nodeTarget $NODE_VERSION
RUN cd $ROOT_APPLICATION && npx --yes node-llama-cpp build --nodeTarget $NODE_VERSION
```

Thanks

**Comment by giladgd** [comment]
@loretoparisi Your use of the documentation is incorrect as I already explained in this comment: https://github.com/withcatai/node-llama-cpp/issues/24#issuecomment-1702931862

**Comment by loretoparisi** [comment]
> @loretoparisi Your use of `node-llama-cpp` is incorrect and inconsistent with the documentation as I already explained in this comment: https://github.com/withcatai/node-llama-cpp/issues/24#issuecomment-1702931862

thank you the error was in the path sent to the tags api, fixed thanks!
