### ISSUE TITLE
Installation with CUDA-support fails early with "npm ERR! canceled"

### ISSUE THREAD

**Issue by itinance** [withcatai/node-llama-cpp#301]
### Issue description

npm ERR! canceled

### Expected Behavior

I would expect to get it installed on my CUDA instance

### Actual Behavior

npm ERR! canceled
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2024-08-19T09_06_29_513Z-debug-0.log

### Steps to reproduce

`npx --no node-llama-cpp download --cuda`

npm ERR! canceled

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |           Ubuntu 22          |
| CPU                      | x86_64 |
| Node.js version          | v12.22.9             |
| Typescript version       | x.y.zzz             |
| `node-llama-cpp` version | latest             |

### Additional Context

Logs:

0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/share/nodejs/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--no-yes',
0 verbose cli   'node-llama-cpp',
0 verbose cli   '--',
0 verbose cli   'download',
0 verbose cli   '--cuda'
0 verbose cli ]
1 info using npm@8.5.1
2 info using node@v12.22.9
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/xxx/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 5ms
18 timing npm:load:configload Completed in 5ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 1ms
21 timing npm:load:display Completed in 2ms
22 verbose logfile /home/xxxxx/.npm/_logs/2024-08-19T09_05_29_434Z-debug-0.log
23 timing npm:load:logFile Completed in 2ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 10ms
27 http fetch GET 200 https://registry.npmjs.org/node-llama-cpp 587ms (cache miss)
28 timing arborist:ctor Completed in 0ms
29 timing arborist:ctor Completed in 0ms
30 timing command:exec Completed in 602ms
31 verbose stack Error: canceled
31 verbose stack     at exec (/usr/share/nodejs/npm/node_modules/libnpmexec/lib/index.js:157:17)
31 verbose stack     at async module.exports (/usr/share/nodejs/npm/lib/cli.js:66:5)
32 verbose cwd /home/xxx
33 verbose Linux 5.15.0-118-generic
34 verbose argv "/usr/bin/node" "/usr/share/nodejs/npm/bin/npm-cli.js" "exec" "--no-yes" "node-llama-cpp" "--" "download" "--cuda"
35 verbose node v12.22.9
36 verbose npm  v8.5.1
37 error canceled
38 verbose exit 1
39 timing npm Completed in 767ms
40 verbose code 1
41 error A complete log of this run can be found in:
41 error     /home/xxx/.npm/_logs/2024-08-19T09_05_29_434Z-debug-0.log

### Relevant Features Used

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by itinance** [comment]
It works perfectly with latest node-version 22.

For some reasons, Ubuntu 22 comes shipped with a dead old version of Node (Node 12, from 2022!). Upgrading NodeJS to 22 allowed me to install this library with CUDA-Support. Works perfectly.
